export const defaultCategories = [
    { "id": "12jkmb-ased21-alc21", "source": "user", "name": "Stretching", "color": "yellow" },
    { "id": "12jkmb-ased21-alc22", "source": "user", "name": "Strength", "color": "blue" },
    { "id": "12jkmb-ased21-alc23", "source": "user", "name": "Cardio", "color": "red" },
    { "id": "12jkmb-ased21-alc24", "source": "user", "name": "Flexibility", "color": "green" },
    { "id": "12jkmb-ased21-alc25", "source": "user", "name": "Mobility", "color": "purple" },
    { "id": "12jkmb-ased21-alc26", "source": "user", "name": "Endurance", "color": "orange" },
    { "id": "12jkmb-ased21-alc27", "source": "user", "name": "Balance", "color": "pink" },
    { "id": "12jkmb-ased21-alc28", "source": "user", "name": "Rehabilitation", "color": "brown" },
    { "id": "12jkmb-ased21-alc29", "source": "user", "name": "Weight Loss", "color": "lightblue" },
    { "id": "12jkmb-ased21-alc30", "source": "user", "name": "Muscle Gain", "color": "lightgreen" },
    { "id": "12jkmb-ased21-alc31", "source": "user", "name": "Core", "color": "yellowgreen" },
    { "id": "12jkmb-ased21-alc32", "source": "user", "name": "Full Body", "color": "redorange" },
    { "id": "12jkmb-ased21-alc33", "source": "user", "name": "Lower Body", "color": "skyblue" },
    { "id": "12jkmb-ased21-alc34", "source": "user", "name": "Upper Body", "color": "violet" },
    { "id": "12jkmb-ased21-alc35", "source": "user", "name": "Glutes", "color": "lightyellow" },
    { "id": "12jkmb-ased21-alc36", "source": "user", "name": "Quads", "color": "lightpink" },
    { "id": "12jkmb-ased21-alc37", "source": "user", "name": "Hamstrings", "color": "peach" },
    { "id": "12jkmb-ased21-alc38", "source": "user", "name": "Calves", "color": "lavender" },
    { "id": "12jkmb-ased21-alc39", "source": "user", "name": "Shoulders", "color": "darkblue" },
    { "id": "12jkmb-ased21-alc40", "source": "user", "name": "Back", "color": "darkgreen" },
    { "id": "12jkmb-ased21-alc41", "source": "user", "name": "Chest", "color": "coral" },
    { "id": "12jkmb-ased21-alc42", "source": "user", "name": "Arms", "color": "lightpurple" },
    { "id": "12jkmb-ased21-alc43", "source": "user", "name": "Abs", "color": "peachpuff" },
    { "id": "12jkmb-ased21-alc44", "source": "user", "name": "Neck", "color": "mint" },
    { "id": "12jkmb-ased21-alc45", "source": "user", "name": "Posture", "color": "teal" },
    { "id": "12jkmb-ased21-alc46", "source": "user", "name": "Joint Health", "color": "turquoise" }
  ]