export const defaultTags = [
    { "id": "as7j-ksdf6-01saik1", "source": "system", "name": "Hip Flexors", "color": "blue" },
    { "id": "as7j-ksdf6-02saik2", "source": "system", "name": "No Equipment", "color": "green" },
    { "id": "as7j-ksdf6-03saik3", "source": "system", "name": "Stretching", "color": "yellow" },
    { "id": "as7j-ksdf6-04saik4", "source": "system", "name": "Quick", "color": "orange" },
    { "id": "as7j-ksdf6-05saik5", "source": "system", "name": "Strength", "color": "red" },
    { "id": "as7j-ksdf6-06saik6", "source": "system", "name": "Core", "color": "purple" },
    { "id": "as7j-ksdf6-07saik7", "source": "system", "name": "Full Body", "color": "blue" },
    { "id": "as7j-ksdf6-08saik8", "source": "system", "name": "Flexibility", "color": "cyan" },
    { "id": "as7j-ksdf6-09saik9", "source": "system", "name": "Endurance", "color": "green" },
    { "id": "as7j-ksdf6-10saik10", "source": "system", "name": "Balance", "color": "pink" },
    { "id": "as7j-ksdf6-11saik11", "source": "system", "name": "Lower Body", "color": "brown" },
    { "id": "as7j-ksdf6-12saik12", "source": "system", "name": "Upper Body", "color": "gray" },
    { "id": "as7j-ksdf6-13saik13", "source": "system", "name": "Cardio", "color": "red" },
    { "id": "as7j-ksdf6-14saik14", "source": "system", "name": "Beginner", "color": "lime" },
    { "id": "as7j-ksdf6-15saik15", "source": "system", "name": "Intermediate", "color": "teal" },
    { "id": "as7j-ksdf6-16saik16", "source": "system", "name": "Advanced", "color": "black" },
    { "id": "as7j-ksdf6-17saik17", "source": "system", "name": "HIIT", "color": "orange" },
    { "id": "as7j-ksdf6-18saik18", "source": "system", "name": "Strength Training", "color": "blue" },
    { "id": "as7j-ksdf6-19saik19", "source": "system", "name": "Pilates", "color": "pink" },
    { "id": "as7j-ksdf6-20saik20", "source": "system", "name": "Yoga", "color": "purple" },
    { "id": "as7j-ksdf6-21saik21", "source": "system", "name": "Rehabilitation", "color": "green" },
    { "id": "as7j-ksdf6-22saik22", "source": "system", "name": "Mobility", "color": "cyan" },
    { "id": "as7j-ksdf6-23saik23", "source": "system", "name": "Recovery", "color": "yellow" },
    { "id": "as7j-ksdf6-24saik24", "source": "system", "name": "Stretch", "color": "orange" },
    { "id": "as7j-ksdf6-25saik25", "source": "system", "name": "Low Impact", "color": "#D1E8E2" }
  ]