export const defaultTags = [
  { _id: "1", name: "At Home", color: "#3498DB", author: "system", category: "activity" },
  { _id: "2", name: "Quick", color: "#E67E22", author: "system", category: "activity" },
  { _id: "3", name: "No Equipment", color: "#2ECC71", author: "system", category: "activity" },
  { _id: "4", name: "Bodyweight", color: "#9B59B6", author: "system", category: "activity" },
  { _id: "5", name: "Beginner Friendly", color: "#1ABC9C", author: "system", category: "activity" },
  { _id: "6", name: "Posture", color: "#F1C40F", author: "system", category: "activity" },
  { _id: "7", name: "Balance", color: "#8E44AD", author: "system", category: "activity" },
  { _id: "8", name: "Low Impact", color: "#27AE60", author: "system", category: "activity" },
  { _id: "9", name: "High Intensity", color: "#E74C3C", author: "system", category: "activity" },
  { _id: "10", name: "Strength Focus", color: "#34495E", author: "system", category: "activity" },

  { _id: "11", name: "Fat Burn", color: "#D35400", author: "system", category: "activity" },
  { _id: "12", name: "Mobility", color: "#00CEC9", author: "system", category: "activity" },
  { _id: "13", name: "Flexibility", color: "#6C5CE7", author: "system", category: "activity" },
  { _id: "14", name: "Core Stability", color: "#E84393", author: "system", category: "activity" },
  { _id: "15", name: "Cardio Boost", color: "#F39C12", author: "system", category: "activity" },
  { _id: "16", name: "Full Body", color: "#2980B9", author: "system", category: "activity" },
  { _id: "17", name: "Upper Body Focus", color: "#9B59B6", author: "system", category: "activity" },
  { _id: "18", name: "Lower Body Focus", color: "#16A085", author: "system", category: "activity" },
  { _id: "19", name: "Short Duration", color: "#2C3E50", author: "system", category: "activity" },
  { _id: "20", name: "Long Duration", color: "#F39C12", author: "system", category: "activity" },

  { _id: "21", name: "Daily Routine", color: "#27AE60", author: "system", category: "activity" },
  { _id: "22", name: "Desk Break", color: "#8E44AD", author: "system", category: "activity" },
  { _id: "23", name: "Energy Boost", color: "#E67E22", author: "system", category: "activity" },
  { _id: "24", name: "Active Recovery", color: "#3498DB", author: "system", category: "activity" },
  { _id: "25", name: "Stretch Focus", color: "#F1C40F", author: "system", category: "activity" },
  { _id: "26", name: "Back Friendly", color: "#1ABC9C", author: "system", category: "activity" },
  { _id: "27", name: "No Jumping", color: "#34495E", author: "system", category: "activity" },
  { _id: "28", name: "Knee Friendly", color: "#C0392B", author: "system", category: "activity" },
  { _id: "29", name: "Quiet Workout", color: "#2ECC71", author: "system", category: "activity" },
  { _id: "30", name: "Outdoors", color: "#16A085", author: "system", category: "activity" },

  { _id: "31", name: "Indoors", color: "#2980B9", author: "system", category: "activity" },
  { _id: "32", name: "No Mat Needed", color: "#E74C3C", author: "system", category: "activity" },
  { _id: "33", name: "Morning Routine", color: "#F39C12", author: "system", category: "activity" },
  { _id: "34", name: "Evening Routine", color: "#8E44AD", author: "system", category: "activity" },
  { _id: "35", name: "Stretch and Relax", color: "#00CEC9", author: "system", category: "activity" },
  { _id: "36", name: "Burn Calories", color: "#E84393", author: "system", category: "activity" },
  { _id: "37", name: "Fatigue Recovery", color: "#6C5CE7", author: "system", category: "activity" },
  { _id: "38", name: "No Shoes Needed", color: "#2C3E50", author: "system", category: "activity" },
  { _id: "39", name: "Home Gym", color: "#27AE60", author: "system", category: "activity" },
  { _id: "40", name: "Minimalist", color: "#D35400", author: "system", category: "activity" },

  { _id: "41", name: "Low Energy", color: "#F1C40F", author: "system", category: "activity" },
  { _id: "42", name: "Standing Only", color: "#8E44AD", author: "system", category: "activity" },
  { _id: "43", name: "Chair Workout", color: "#3498DB", author: "system", category: "activity" },
  { _id: "44", name: "Sitting Workout", color: "#E67E22", author: "system", category: "activity" },
  { _id: "45", name: "Quiet Environment", color: "#1ABC9C", author: "system", category: "activity" },
  { _id: "46", name: "Short Break", color: "#E74C3C", author: "system", category: "activity" },
  { _id: "47", name: "On the Go", color: "#34495E", author: "system", category: "activity" },
  { _id: "48", name: "Travel Friendly", color: "#2ECC71", author: "system", category: "activity" },
  { _id: "49", name: "Low Space", color: "#9B59B6", author: "system", category: "activity" },
  { _id: "50", name: "Mindful Movement", color: "#F39C12", author: "system", category: "activity" }
];
