export const muscles = [
  { name: "Arms", value: "arms" },
  { name: "Legs", value: "legs" },
  { name: "Chest", value: "chest" },
  { name: "Back", value: "back" },
  { name: "Core", value: "core" },
  { name: "Shoulders", value: "shoulders" },
  { name: "Neck", value: "neck" },
  // Specific muscles
  { name: "Biceps", value: "biceps" },
  { name: "Triceps", value: "triceps" },
  { name: "Forearms", value: "forearms" },
  { name: "Quadriceps", value: "quadriceps" },
  { name: "Hamstrings", value: "hamstrings" },
  { name: "Calves", value: "calves" },
  { name: "Glutes", value: "glutes" },
  { name: "Abs", value: "abs" },
  { name: "Obliques", value: "obliques" },
  { name: "Upper Back", value: "upper-back" },
  { name: "Lower Back", value: "lower-back" },
  { name: "Lats", value: "lats" },
  { name: "Traps", value: "traps" },
  { name: "Deltoids", value: "deltoids" },
  { name: "Pecs", value: "pecs" },
  { name: "Hip Flexors", value: "hip-flexors" },
  { name: "Adductors", value: "adductors" },
  { name: "Abductors", value: "abductors" },
  { name: "Erector Spinae", value: "erector-spinae" },
  { name: "Rotator Cuff", value: "rotator-cuff" },
  { name: "Serratus Anterior", value: "serratus-anterior" },
  { name: "Rhomboids", value: "rhomboids" },
  { name: "Sternocleidomastoid", value: "sternocleidomastoid" }
];
