export const defaultTargetGroups = [
    { "id": "54sd-64fff-gf32", "source": "system", "name": "Hip Flexors" },
    { "id": "54sd-64fff-gf33", "source": "system", "name": "Core" },
    { "id": "54sd-64fff-gf34", "source": "system", "name": "Upper Body" },
    { "id": "54sd-64fff-gf35", "source": "system", "name": "Lower Body" },
    { "id": "54sd-64fff-gf36", "source": "system", "name": "Glutes" },
    { "id": "54sd-64fff-gf37", "source": "system", "name": "Quads" },
    { "id": "54sd-64fff-gf38", "source": "system", "name": "Hamstrings" },
    { "id": "54sd-64fff-gf39", "source": "system", "name": "Calves" },
    { "id": "54sd-64fff-gf40", "source": "system", "name": "Shoulders" },
    { "id": "54sd-64fff-gf41", "source": "system", "name": "Back" },
    { "id": "54sd-64fff-gf42", "source": "system", "name": "Chest" },
    { "id": "54sd-64fff-gf43", "source": "system", "name": "Arms" },
    { "id": "54sd-64fff-gf44", "source": "system", "name": "Abs" },
    { "id": "54sd-64fff-gf45", "source": "system", "name": "Neck" },
    { "id": "54sd-64fff-gf46", "source": "system", "name": "Full Body" },
    { "id": "54sd-64fff-gf47", "source": "system", "name": "Cardio" },
    { "id": "54sd-64fff-gf48", "source": "system", "name": "Strength" },
    { "id": "54sd-64fff-gf49", "source": "system", "name": "Flexibility" },
    { "id": "54sd-64fff-gf50", "source": "system", "name": "Mobility" },
    { "id": "54sd-64fff-gf51", "source": "system", "name": "Balance" },
    { "id": "54sd-64fff-gf52", "source": "system", "name": "Endurance" },
    { "id": "54sd-64fff-gf53", "source": "system", "name": "Rehabilitation" },
    { "id": "54sd-64fff-gf54", "source": "system", "name": "Posture" },
    { "id": "54sd-64fff-gf55", "source": "system", "name": "Weight Loss" },
    { "id": "54sd-64fff-gf56", "source": "system", "name": "Muscle Gain" },
    { "id": "54sd-64fff-gf57", "source": "system", "name": "Joint Health" }
  ]